const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const root = {state:{analysis:{analysis_id:'first',assessment:{included:['虚拟甲','Virtual Beta']},experts:[{expert_name:'虚拟甲'},{expert_name:'Virtual Beta'},{expert_name:'虚拟未纳入'}]}},document:{addEventListener(){}},escapeHtml:s=>s};
vm.createContext(root);
vm.runInContext(fs.readFileSync('src/web/reviewer-filter.js','utf8'),root);
assert.equal(root.objectiveReviewers().length,2);
vm.runInContext("objectiveFilter.names=new Set(['Virtual Beta'])",root);
assert.equal(root.objectiveReviewerVisible('虚拟甲'),false);
assert.equal(root.objectiveReviewerVisible('Virtual Beta'),true);
assert.match(root.objectiveReviewerHeader(),/已选1人/);
assert.equal(root.state.analysis.assessment.included.length,2);
vm.runInContext('objectiveFilter.names=new Set()',root);
assert.match(root.objectiveReviewerHeader(),/已选0人/);
root.state.analysis.analysis_id='second';
root.objectiveReviewers();
assert.equal(root.objectiveReviewerVisible('虚拟甲'),true);
assert.match(root.objectiveReviewerHeader(),/全部/);
root.window={addEventListener(){}};
vm.runInContext(fs.readFileSync('src/web/facts.js','utf8'),root);
const scroller={scrollLeft:357.5,classList:{add(){}},setAttribute(){},addEventListener(){throw Error('No competing scroll handler should overwrite native drag');}};
root.makeTableScrollable(scroller);
assert.equal(scroller.scrollLeft,357.5);
root.makeTableScrollable(scroller);
assert.equal(scroller.scrollLeft,357.5);
console.log('评审人筛选回归：交集、独立显示状态、空选、新分析重置；横向滚动位置保留通过');
const app = fs.readFileSync('src/web/app.js', 'utf8');
vm.runInContext(app.slice(app.indexOf('function normalizedReviewerSearch'), app.indexOf('async function downloadDimensionOne')), root);
const person = {expert_name:'虚拟甲',expert_name_pinyin:'xu ni jia',expert_name_initials:'xnj'};
assert.equal(root.reviewerMatchesSearch(person,'乙  XUNIJIA'),true);
assert.equal(root.reviewerMatchesSearch(person,'虚拟甲 nonexistent'),true);
assert.equal(root.reviewerMatchesSearch(person,'xnj'),false);
assert.equal(root.reviewerMatchesSearch(person,'   '),true);
const elements = {'#reviewer-filter-search':{value:'虚拟甲'}, '#reviewer-filter-all':{}, '#reviewer-filter-count':{}};
root.document.querySelector = selector => elements[selector];
root.updateReviewerSelectAll();
assert.equal(elements['#reviewer-filter-all'].checked,true);
vm.runInContext("objectiveFilter.names=new Set(['Virtual Beta'])",root);
elements['#reviewer-filter-search'].value='';
root.updateReviewerSelectAll();
assert.equal(elements['#reviewer-filter-all'].indeterminate,true);
assert.equal(elements['#reviewer-filter-all'].checked,false);
elements['#reviewer-filter-search'].value='不存在';
root.updateReviewerSelectAll();
assert.equal(elements['#reviewer-filter-all'].disabled,true);
assert.equal(elements['#reviewer-filter-all'].indeterminate,false);
console.log('姓名／全拼多关键词任一匹配、半选及空结果禁用通过');
