const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const root = {state:{analysis:{analysis_id:'first',assessment:{included:['虚拟甲','Virtual Beta']},experts:[{expert_name:'虚拟甲'},{expert_name:'Virtual Beta'},{expert_name:'虚拟未纳入'}]}},document:{addEventListener(){}},escapeHtml:s=>s};
vm.createContext(root);
vm.runInContext(fs.readFileSync('src/web/reviewer-filter.js','utf8'),root);
assert.equal(root.objectiveReviewers().length,2);
vm.runInContext("objectiveFilter.names=new Set(['Virtual Beta'])",root);
assert.equal(root.objectiveReviewerVisible('虚拟甲'),false);
assert.equal(root.objectiveReviewerVisible('Virtual Beta'),true);
assert.match(root.objectiveReviewerHeader(),/已选1人/);
assert.equal(root.state.analysis.assessment.included.length,2);
vm.runInContext('objectiveFilter.names=new Set()',root);
assert.match(root.objectiveReviewerHeader(),/已选0人/);
root.state.analysis.analysis_id='second';
root.objectiveReviewers();
assert.equal(root.objectiveReviewerVisible('虚拟甲'),true);
assert.match(root.objectiveReviewerHeader(),/全部/);
root.window={addEventListener(){}};
vm.runInContext(fs.readFileSync('src/web/facts.js','utf8'),root);
const scroller={scrollLeft:357.5,classList:{add(){}},setAttribute(){},addEventListener(){throw Error('No competing scroll handler should overwrite native drag');}};
root.makeTableScrollable(scroller);
assert.equal(scroller.scrollLeft,357.5);
root.makeTableScrollable(scroller);
assert.equal(scroller.scrollLeft,357.5);
console.log('评审人筛选回归：交集、独立显示状态、空选、新分析重置；横向滚动位置保留通过');
